name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      working-directory: ./shopping-tracker

    - name: Start the application
      run: npm start & npx wait-on http://localhost:3000
      working-directory: ./shopping-tracker

    - name: Run tests
      run: npx cypress run
      working-directory: ./shopping-tracker
      
    - name: Build
      run: npm run build
      working-directory: ./shopping-tracker

    - name: Deploy on GH-Pages
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'AmirDebbie'
        user_email: 'amird812@gmail.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
      working-directory: ./shopping-tracker
